// personnages.js

const personnages = [
  {
    nom: "Alice",
    age: 28,
    avatar: "./avatar/alice.jpg",
    description: "Magicienne talentueuse",
    victoire: "La magie est mon alliée",
    signe: "A",
    phrase: "Que la magie soit avec moi",
  },
  {
    nom: "Charlie",
    age: 30,
    avatar: "./avatar/charlie.jpg",
    description: "Champion de l'escalade",
    victoire: "J'atteins toujours le sommet",
    signe: "C",
    phrase: "La montagne m'appelle",
  },
  {
    nom: "Eva",
    age: 26,
    avatar: "./avatar/eva.jpg",
    description: "Ingénieure créative",
    victoire: "L'innovation est mon arme",
    signe: "E",
    phrase: "Construisons un avenir meilleur",
  },
  {
    nom: "Frankie",
    age: 40,
    avatar: "./avatar/frankie.jpg",
    description: "Chasseur de trésors intrépide",
    victoire: "L'or n'a pas de secrets pour moi",
    signe: "F",
    phrase: "À la recherche de l'or perdu",
  },
  {
    nom: "Olivia",
    age: 22,
    avatar: "./avatar/olivia.jpg",
    description: "Aventurière enthousiaste",
    victoire: "L'excitation est ma compagne",
    signe: "O",
    phrase: "Vers l'inconnu et au-delà",
  },
  {
    nom: "Sailor Moon",
    age: 16,
    avatar: "./avatar/sailor Moon.jpg",
    description: "Gardienne de l'amour et de la justice",
    victoire: "Au nom de la Lune, je te punirai!",
    signe: "S",
    phrase: "L'amour et la paix triompheront toujours.",
  },
  {
    nom: "Naruto Uzumaki",
    age: 17,
    avatar: "./avatar/naruto uzumaki.jpg",
    description: "Ninja aux rêves de devenir Hokage",
    victoire: "Je ne reviens jamais sur ma parole!",
    signe: "N",
    phrase: "Je vais devenir le plus grand ninja!",
  },
  {
    nom: "Monkey D. Luffy",
    age: 19,
    avatar: "./avatar/monkey D. Luffy.jpg",
    description: "Capitaine des Pirates au Chapeau de Paille",
    victoire: "Je serai le Roi des Pirates!",
    signe: "M",
    phrase: "Je ne recule devant rien pour atteindre mon rêve.",
  },
  {
    nom: "Goku",
    age: 35,
    avatar: "./avatar/goku.jpg",
    description: "Saiyan légendaire et défenseur de la Terre",
    victoire: "Kamehameha!",
    signe: "G",
    phrase: "Je suis le guerrier le plus fort de l'univers!",
  },
  {
    nom: "Sakura Kinomoto",
    age: 13,
    avatar: "./avatar/Sakura Kinomoto.jpg",
    description: "Magicienne en herbe",
    victoire: "Carte Clow, change de forme!",
    signe: "S",
    phrase: "Que la magie guide mon chemin.",
  },
  {
    nom: "Harry Potter",
    age: 17,
    avatar: "./avatar/Harry Potter.jpg",
    description: "Le sorcier qui a survécu à Voldemort",
    victoire: "Expelliarmus!",
    signe: "P",
    phrase: "Je suis un sorcier, Harry.",
  },
  {
    nom: "Hermione Granger",
    age: 18,
    avatar: "./avatar/Hermione Granger.jpg",
    description: "L'intelligente et talentueuse sorcière",
    victoire: "Accio!",
    signe: "H",
    phrase: "Quand tu ne sais pas, demande à Hermione.",
  },
  {
    nom: "Ron Weasley",
    age: 18,
    avatar: "./avatar/Ron Weasley.jpg",
    description: "Le fidèle ami et camarade de Harry",
    victoire: "Alohomora!",
    signe: "R",
    phrase: "Moi ? Conduire la voiture volante ?",
  },
  {
    nom: "Dumbledore",
    age: 115,
    avatar: "./avatar/Dumbledore.jpg",
    description: "Le directeur de Poudlard",
    victoire: "Nitwit! Blubber! Oddment! Tweak!",
    signe: "D",
    phrase: "N'ayez pas peur de faire ce que vous savez être juste.",
  },
  {
    nom: "Bulma",
    age: 30,
    avatar: "./avatar/Bulma.png",
    description: "Scientifique brillante et aventurière",
    victoire: "Capsule Corp!",
    signe: "B",
    phrase: "L'avenir est fait de science et d'aventure.",
  },
  {
    nom: "Sophie",
    age: 25,
    avatar: "./avatar/sophie.jpg",
    description: "Artiste peintre talentueuse",
    victoire: "Les couleurs sont mon langage",
    signe: "So",
    phrase: "Je peins le monde à ma façon",
  },
  {
    nom: "Léa",
    age: 29,
    avatar: "./avatar/lea.jpg",
    description: "Exploratrice intrépide",
    victoire: "La découverte est ma passion",
    signe: "L",
    phrase: "À la recherche de l'inconnu",
  },
  {
    nom: "Camille",
    age: 31,
    avatar: "./avatar/camille.jpg",
    description: "Astronome éminente",
    victoire: "Les étoiles me guident",
    signe: "Ca",
    phrase: "À la conquête de l'univers",
  },
  // Ajoutez d'autres personnages ici
];

// Exportez les données des personnages
export { personnages };
