// personnages.js

const personnages = [
  {
    nom: "Alice",
    age: 28,
    avatar: "./avatar/alice.jpg",
    description: "Magicienne talentueuse",
    victoire: [
      "La magie est mon alliée.",
      "La magie triomphe encore !",
      "Mes pouvoirs sont inégalés !",
      "Une victoire digne d'une magicienne !",
      "Le spectacle continue avec moi !",
      "La magie est mon alliée, et avec elle, la victoire est inévitable !",
      "La magie triomphe encore grâce à mon talent et ma détermination !",
      "Mes pouvoirs sont inégalés, et chaque victoire est une démonstration de ma maîtrise magique !",
      "Une victoire digne d'une magicienne, car je suis la reine du spectacle magique !",
      "Le spectacle continue avec moi, car je suis Alice, la magicienne qui enflamme le public !",
    ],
    signe: "A",
    phrase: "Que la magie soit avec moi",
  },
  {
    nom: "Charlie",
    age: 30,
    avatar: "./avatar/charlie.jpg",
    description: "Championne de l'escalade",
    victoire: [
      "J'atteins toujours le sommet.",
      "Le sommet est à moi !",
      "Une autre victoire au sommet !",
      "Je suis la reine de la montagne !",
      "La montagne m'obéit toujours !",
      "J'atteins toujours le sommet, car je suis la reine de la montagne !",
      "Le sommet est à moi, et chaque victoire est un pas de plus vers l'apogée !",
      "Une autre victoire au sommet, car la montagne m'obéit toujours !",
      "Je suis la reine de la montagne, et aucun défi n'est trop grand pour moi !",
      "La montagne m'appelle, et je réponds en conquérant chaque sommet !",
    ],
    signe: "C",
    phrase: "La montagne m'appelle",
  },
  {
    nom: "Eva",
    age: 26,
    avatar: "./avatar/eva.jpg",
    description: "Ingénieure créative",
    victoire: [
      "L'innovation est mon arme.",
      "L'innovation l'emporte encore !",
      "Mon esprit créatif triomphe !",
      "Un avenir meilleur commence avec moi !",
      "Chaque victoire est une innovation !",
      "L'innovation est mon arme secrète, et avec elle, je remporte la victoire à chaque fois !",
      "L'innovation l'emporte encore, car mon esprit créatif est inépuisable !",
      "Mon esprit créatif triomphe, et chaque victoire construit un avenir meilleur !",
      "Un avenir meilleur commence avec moi, car je suis déterminée à innover sans relâche !",
      "Chaque victoire est une innovation, car je suis Eva, l'ingénieure qui construit un avenir brillant !",
    ],
    signe: "E",
    phrase: "Construisons un avenir meilleur",
  },
  {
    nom: "Frankie",
    age: 40,
    avatar: "./avatar/frankie.jpg",
    description: "Chasseur de trésors intrépide",
    victoire: [
      "L'or n'a pas de secrets pour moi.",
      "Je suis la reine des chasseuses de trésors.",
      "Une autre fortune trouvée !",
      "Chaque victoire est une pièce d'or de plus.",
      "Les trésors du monde m'appartiennent !",
      "L'or n'a pas de secrets pour moi, et chaque victoire est une pièce d'or de plus dans ma collection !",
      "Je suis la reine des chasseuses de trésors, et je dévoile les richesses cachées du monde !",
      "Une autre fortune trouvée ! Chaque victoire est un trésor de plus dans ma quête infinie !",
      "Les trésors du monde m'appartiennent, et je les découvre un par un grâce à ma détermination intrépide !",
      "À la recherche de l'or perdu, chaque victoire me rapproche de la découverte du trésor ultime !",
    ],
    signe: "F",
    phrase: "À la recherche de l'or perdu",
  },
  {
    nom: "Olivia",
    age: 22,
    avatar: "./avatar/olivia.jpg",
    description: "Aventurière enthousiaste",
    victoire: [
      "L'excitation est ma compagne.",
      "L'aventure est mon véritable trésor.",
      "Vers de nouvelles aventures gagnantes !",
      "L'inconnu n'a rien sur moi !",
      "L'excitation est le carburant de ma victoire !",
      "L'excitation est ma compagne dans chaque victoire, car l'aventure est mon véritable trésor !",
      "L'aventure est mon véritable trésor, et je me lance vers de nouvelles aventures gagnantes avec enthousiasme !",
      "Vers de nouvelles aventures gagnantes ! L'inconnu n'a rien sur moi, car je suis l'aventurière enthousiaste !",
      "L'excitation est le carburant de ma victoire, et je poursuis chaque aventure avec passion et détermination !",
      "Vers l'inconnu et au-delà, chaque victoire est une étape vers de nouvelles découvertes passionnantes et des aventures sans fin !",
    ],
    signe: "O",
    phrase: "Vers l'inconnu et au-delà",
  },
  {
    nom: "Sailor Moon",
    age: 16,
    avatar: "./avatar/sailor Moon.jpg",
    description: "Gardienne de l'amour et de la justice",
    victoire: [
      "Au nom de la Lune, je te punirai!",
      "Le pouvoir de l'amour et de la justice gagne toujours.",
      "L'éclat de la Lune brille dans ma victoire.",
      "L'amour et la paix triompheront toujours.",
      "La Lune est le symbole de ma victoire !",
      "Au nom de la Lune, je te punirai ! Le pouvoir de l'amour et de la justice gagne toujours !",
      "Le pouvoir de l'amour et de la justice gagne toujours, car l'éclat de la Lune brille dans ma victoire !",
      "L'amour et la paix triompheront toujours, car je suis Sailor Moon, la gardienne de l'amour et de la justice !",
      "La Lune est le symbole de ma victoire, et j'utilise son éclat pour protéger l'amour et la paix dans le monde !",
      "L'amour et la paix triompheront toujours, car je suis déterminée à protéger le monde au nom de la Lune et de la justice !",
    ],
    signe: "S",
    phrase: "L'amour et la paix triompheront toujours.",
  },
  {
    nom: "Naruto Uzumaki",
    age: 17,
    avatar: "./avatar/naruto uzumaki.jpg",
    description: "Ninja aux rêves de devenir Hokage",
    victoire: [
      "Je ne reviens jamais sur ma parole!",
      "Je suis le Hokage du futur !",
      "Les rêves deviennent réalité avec moi !",
      "Le Hokage en herbe remporte encore une victoire !",
      "Je suis Naruto Uzumaki, le ninja le plus puissant !",
      "Je ne reviens jamais sur ma parole! Mon chemin vers le Hokage est marqué par la victoire !",
      "Je suis le Hokage du futur, et ma détermination m'apporte des victoires sans fin !",
      "Les rêves deviennent réalité avec moi, le Hokage en herbe triomphe toujours !",
      "Le Hokage en devenir remporte encore une victoire, car je suis Naruto Uzumaki, le ninja le plus puissant !",
      "Je vais devenir le plus grand ninja, et chaque victoire m'approche de cet objectif !",
    ],
    signe: "N",
    phrase: "Je vais devenir le plus grand ninja!",
  },
  {
    nom: "Monkey D. Luffy",
    age: 19,
    avatar: "./avatar/monkey D. Luffy.jpg",
    description: "Capitaine des Pirates au Chapeau de Paille",
    victoire: [
      "Je serai le Roi des Pirates!",
      "Le Roi des Pirates ne connaît pas de défaite !",
      "Chaque victoire m'approche de mon rêve !",
      "Le chapeau de paille représente la victoire !",
      "Je suis Monkey D. Luffy, le futur Roi des Pirates !",
      "Je serai le Roi des Pirates ! Chaque victoire me rapproche de mon rêve ultime !",
      "Le Roi des Pirates ne connaît pas de défaite, car je ne recule devant rien pour atteindre mon rêve !",
      "Le chapeau de paille représente la victoire, et je suis Monkey D. Luffy, le futur Roi des Pirates !",
      "Avec chaque victoire, je me rapproche de la Grand Line et de mon rêve ultime de devenir le Roi des Pirates !",
      "Je ne recule devant rien pour atteindre mon rêve, car je suis déterminé à devenir le Roi des Pirates !",
    ],
    signe: "M",
    phrase: "Je ne recule devant rien pour atteindre mon rêve.",
  },
  {
    nom: "Goku",
    age: 35,
    avatar: "./avatar/goku.jpg",
    description: "Saiyan légendaire et défenseur de la Terre",
    victoire: [
      "Kamehameha!",
      "Mon pouvoir est sans limites !",
      "Je suis le guerrier ultime de l'univers !",
      "Kamehameha ! La victoire est à moi !",
      "Goku, le Saiyan légendaire, triomphe toujours !",
      "Kamehameha! Mon pouvoir est sans limites, et la victoire est toujours à ma portée !",
      "Je suis le guerrier ultime de l'univers, et chaque Kamehameha signifie une victoire inévitable !",
      "Kamehameha ! La victoire est à moi, car je suis Goku, le Saiyan légendaire qui triomphe toujours !",
      "Mon pouvoir Saiyan ne connaît pas de limites, et chaque victoire renforce ma réputation de guerrier inégalé !",
      "Je suis le guerrier le plus fort de l'univers, et chaque bataille m'apporte une nouvelle victoire !",
    ],
    signe: "G",
    phrase: "Je suis le guerrier le plus fort de l'univers!",
  },
  {
    nom: "Sakura Kinomoto",
    age: 13,
    avatar: "./avatar/Sakura Kinomoto.jpg",
    description: "Magicienne en herbe",
    victoire: [
      "Carte Clow, change de forme!",
      "La magie est ma meilleure alliée !",
      "Les cartes Clow obéissent à ma victoire !",
      "Que la magie guide mon chemin vers la victoire !",
      "La magicienne en herbe, triomphe encore une fois !",
      "Carte Clow, change de forme ! La magie est ma meilleure alliée pour chaque victoire !",
      "La magie guide mon chemin vers la victoire, car les cartes Clow obéissent à mon pouvoir magique !",
      "Que la magie guide mon chemin vers le succès, car la magicienne en herbe triomphe toujours !",
      "Je suis Sakura Kinomoto, la magicienne en devenir, et chaque victoire est une étape vers la maîtrise des cartes Clow !",
      "La magie est mon atout, et je triomphe encore une fois grâce à la magie et à la détermination !",
    ],
    signe: "S",
    phrase: "Que la magie guide mon chemin.",
  },
  {
    nom: "Harry Potter",
    age: 17,
    avatar: "./avatar/Harry Potter.jpg",
    description: "Le sorcier qui a survécu à Voldemort",
    victoire: [
      "Expelliarmus!",
      "Le sorcier qui a vaincu le plus sombre des sorciers !",
      "Chaque victoire est un pas vers la paix !",
      "Je suis Harry Potter, le survivant !",
      "L'amour triomphe sur le mal !",
      "Expelliarmus! Mon sort signature, la victoire est à moi !",
      "Je suis le sorcier qui a vaincu le plus sombre des sorciers !",
      "Chaque victoire est un pas vers la paix dans le monde magique !",
      "Je suis Harry Potter, le survivant, et j'incarne le triomphe de l'amour sur le mal !",
      "L'amour et l'amitié sont mes plus grands alliés dans la victoire !",
    ],
    signe: "P",
    phrase: "Je suis un sorcier.",
  },
  {
    nom: "Hermione Granger",
    age: 18,
    avatar: "./avatar/Hermione Granger.jpg",
    description: "L'intelligente et talentueuse sorcière",
    victoire: [
      "Accio!",
      "La connaissance est le pouvoir de ma victoire !",
      "Je suis la meilleure dans toutes les matières !",
      "Rien n'est impossible avec la magie !",
      "La sagesse m'accompagne dans la victoire !",
      "Accio! La magie de la connaissance est la clé de ma victoire !",
      "La connaissance est le pouvoir qui m'accompagne vers la victoire !",
      "Je suis la meilleure dans toutes les matières, et ma victoire est inévitable !",
      "Rien n'est impossible avec la magie et la sagesse !",
      "La sagesse est mon atout secret pour toutes les victoires !",
    ],
    signe: "H",
    phrase: "Quand tu ne sais pas, demande à Hermione.",
  },
  {
    nom: "Ron Weasley",
    age: 18,
    avatar: "./avatar/Ron Weasley.jpg",
    description: "Le fidèle ami et camarade de Harry",
    victoire: [
      "Alohomora!",
      "Moi ? Conduire la voiture volante ?",
      "La loyauté est ma force secrète de victoire !",
      "Les amis triomphent toujours ensemble !",
      "Je suis Ron Weasley, le roi des échecs !",
      "Alohomora! La loyauté est la clé de ma victoire !",
      "Moi ? Conduire la voiture volante ? Rien ne m'arrête dans la victoire !",
      "La loyauté et l'amitié sont mes forces secrètes pour triompher !",
      "Les amis triomphent toujours ensemble, c'est mon credo !",
      "Je suis Ron Weasley, le roi des échecs, et je remporte chaque partie de la vie !",
    ],
    signe: "R",
    phrase: "Moi ? Conduire la voiture volante ?",
  },
  {
    nom: "Dumbledore",
    age: 115,
    avatar: "./avatar/Dumbledore.jpg",
    description: "Le directeur de Poudlard",
    victoire: [
      "Nitwit! Blubber! Oddment! Tweak!",
      "La sagesse est la clé de la victoire !",
      "N'ayez pas peur de faire ce que vous savez être juste.",
      "L'éducation est le plus grand pouvoir !",
      "Dumbledore, le sage de Poudlard, triomphe avec sagesse !",
      "Nitwit! Blubber! Oddment! Tweak! La sagesse est la clé de ma victoire !",
      "N'ayez pas peur de faire ce que vous savez être juste, c'est le chemin de la victoire !",
      "L'éducation est le plus grand pouvoir, et il conduit à des victoires durables !",
      "Dumbledore, le sage de Poudlard, triomphe avec sagesse et éducation !",
      "La sagesse et le discernement sont mes alliés pour guider les générations futures vers la victoire !",
    ],
    signe: "D",
    phrase: "N'ayez pas peur de faire ce que vous savez être juste.",
  },
  {
    nom: "Bulma",
    age: 30,
    avatar: "./avatar/Bulma.png",
    description: "Scientifique brillante et aventurière",
    victoire: [
      "Capsule Corp!",
      "La science est ma meilleure alliée !",
      "L'avenir est fait de découvertes technologiques !",
      "Bulma, la scientifique, triomphe encore une fois !",
      "L'innovation est mon alliée dans la victoire !",
      "Capsule Corp! La science est ma meilleure alliée !",
      "L'avenir est fait de découvertes technologiques et de victoires !",
      "Bulma, la scientifique, triomphe encore une fois grâce à l'innovation !",
      "Mes inventions me guident vers la victoire et vers un avenir brillant !",
      "La technologie est mon atout secret pour toutes les victoires !",
    ],
    signe: "B",
    phrase: "L'avenir est fait de science et d'aventure.",
  },
  {
    nom: "Sophie",
    age: 25,
    avatar: "./avatar/sophie.jpg",
    description: "Artiste peintre talentueuse",
    victoire: [
      "Les couleurs sont mon langage.",
      "L'art est ma passion et ma victoire !",
      "Chaque toile est une victoire sur la vie !",
      "Sophie, l'artiste, crée la victoire avec des couleurs !",
      "La beauté de l'art m'accompagne vers la victoire !",
      "Les couleurs sont mon langage, et l'art est ma victoire !",
      "Chaque toile est une victoire sur la vie elle-même !",
      "Sophie, l'artiste, crée la victoire avec chaque coup de pinceau !",
      "La beauté de l'art m'accompagne vers des victoires artistiques inégalées !",
      "Chaque chef-d'œuvre est une victoire sur le monde que je peins à ma façon !",
    ],
    signe: "So",
    phrase: "Je peins le monde à ma façon",
  },
  {
    nom: "Léa",
    age: 29,
    avatar: "./avatar/lea.jpg",
    description: "Exploratrice intrépide",
    victoire: [
      "La découverte est ma passion.",
      "L'exploration m'emmène vers la victoire !",
      "Les terres inconnues sont mon domaine de victoire !",
      "Léa, l'exploratrice intrépide, triomphe à chaque découverte !",
      "Chaque aventure est une victoire dans l'inconnu !",
      "La découverte est ma passion et mon chemin vers la victoire !",
      "L'exploration m'emmène vers des victoires dans les terres inconnues !",
      "Léa, l'exploratrice intrépide, triomphe à chaque découverte dans l'inconnu !",
      "Chaque aventure est une victoire dans le monde mystérieux de l'exploration !",
      "Les terres inexplorées sont mon terrain de victoire, où l'inconnu devient une aventure triomphante !",
    ],
    signe: "L",
    phrase: "À la recherche de l'inconnu",
  },
  {
    nom: "Camille",
    age: 31,
    avatar: "./avatar/camille.jpg",
    description: "Astronome éminente",
    victoire: [
      "Les étoiles me guident.",
      "L'univers est mon terrain de victoire !",
      "L'astronomie m'ouvre la voie de la victoire !",
      "Camille, l'astronome, explore les étoiles pour la victoire !",
      "Les constellations me guident vers de nouvelles victoires !",
      "Les étoiles me guident vers la victoire ultime !",
      "L'univers est mon terrain de prédilection, où chaque découverte est une victoire !",
      "À travers l'astronomie, je trace la voie vers de nouvelles victoires éblouissantes !",
      "Camille, l'astronome, explore les mystères des étoiles pour triompher !",
      "Les constellations sont mes alliées, me guidant vers des conquêtes victorieuses dans l'univers infini !",
    ],
    signe: "Ca",
    phrase: "À la conquête de l'univers",
  },
  {
    nom: "Roxy Miguardia",
    age: 26,
    avatar: "./avatar/roxy.jpg",
    description: "magicienne talentueuse et charismatique",
    victoire: [
      "La magie embrase la victoire une fois de plus !",
      "Mon pouvoir magique est une force inarrêtable !",
      "La magie triomphe comme une étoile brillante dans la nuit !",
      "Une victoire digne d'une magicienne éclairée par la magie !",
      "Le spectacle continue avec la magie à mes côtés !",
      "La magie est mon bras droit, et la victoire est ma destinée !",
      "Les étoiles dansent avec ma magie, marquant une victoire éclatante !",
      "Chaque sort lancé est une note de victoire dans ma symphonie magique !",
      "Avec la magie comme alliée, la victoire est inévitable !",
      "Chaque victoire est un nouveau chapitre de mon histoire magique !",
    ],
    signe: "R",
    phrase: "Que la magie soit avec moi.",
  },
  // Ajoutez d'autres personnages ici
];

const phraseMJ = [
  "Aucun des deux joueurs n'a réussi à prendre l'avantage",
  "L'égalité ! Le destin ne favorise ni l'un ni l'autre. Préparez-vous pour un défi ultime !",
  "C'est un match nul ! Qui aurait pensé que cela se terminerait ainsi ? Une revanche s'impose !",
  "Aucun gagnant ni perdant cette fois ! Une bataille acharnée se poursuit pour déterminer le champion.",
  "Le jeu est suspendu dans un équilibre parfait. Qui brisera cette égalité lors du prochain round ?",
  "Personne ne l'emporte cette fois-ci. C'est une chance de montrer votre véritable force lors du tie-breaker !",
  "L'égalité est le reflet d'une compétition féroce. Qui sortira victorieux de cette impasse ?",
  "Un affrontement acharné ! L'égalité est le signe d'une compétition intense. Préparez-vous pour le round décisif !",
  "Les forces s'équilibrent, et nous entrons dans un round bonus pour déterminer un vainqueur !",
  "C'est un match nul, mais la bataille est loin d'être terminée. Qui sortira victorieux de ce duel acharné ?",
];

// Exportez les données des personnages
export { personnages, phraseMJ };
